-- Recurring training rules: defines weekly recurrence patterns for teams.
-- Actual activity rows are generated by the CMS (Phase 5).
create table if not exists public.recurring_rules (
  id           uuid primary key default gen_random_uuid(),
  team_id      uuid not null references public.teams(id) on delete cascade,
  day_of_week  smallint not null check (day_of_week between 1 and 7), -- 1=maandag, 7=zondag
  start_time   time not null,
  end_time     time,
  location     text,
  notes        text,
  valid_from   date not null,
  valid_until  date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz
);

create index recurring_rules_team_id_idx on public.recurring_rules(team_id);

create trigger recurring_rules_updated_at
  before update on public.recurring_rules
  for each row execute procedure public.handle_updated_at();

-- Link activities to a recurring rule for grouping
alter table public.activities
  add column if not exists recurring_rule_id uuid references public.recurring_rules(id) on delete set null;

create index if not exists activities_recurring_rule_id_idx on public.activities(recurring_rule_id);
create index if not exists activities_type_idx on public.activities(type);

alter table public.recurring_rules enable row level security;

-- Alle ingelogde gebruikers mogen trainingsschema's inzien
create policy "authenticated_select_recurring_rules"
  on public.recurring_rules for select
  using (auth.role() = 'authenticated' and deleted_at is null);

-- Alleen staf mag recurring rules beheren
create policy "staff_manage_recurring_rules"
  on public.recurring_rules for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role in ('beheerder', 'commissielid', 'trainer', 'coach', 'teammanager')
    )
  );
